apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-pods
  labels:
    app: broker
spec:
  serviceName: broker
  replicas: 3
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: broker-pvc
      containers:
        - name: broker-container
          image: doughgle/kafka-kraft
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: REPLICAS
              value: "3"
            - name: SERVICE
              value: kafka-svc
            - name: NAMESPACE
              value: kafka
            - name: SHARE_DIR
              value: /mnt/kafka
            - name: CLUSTER_ID
              value: kb-WV7dt8Au9ixOk4YbRm5tL
            - name: DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: "2"
          volumeMounts:
            - name: kafka-data
              mountPath: /mnt/kafka
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: broker
  name: broker
spec:
  ports:
    - name: "9092"
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: broker