apiVersion: v1
kind: Namespace
metadata:
  name: "kafka"
  labels:
    name: "kafka"
---
- name: sec-file
  secret:
    secretName: broker-secret
---
- name: sec-file
  mountPath: /etc/secret
  readOnly: true
---
volumes:
  - name: kafka-data
    persistentVolumeClaim:
      claimName: broker-pvc
  - name: kafka-config
    configMap:
      name: broker-config
---
volumeMounts:
  - name: kafka-data
    mountPath: /var/lib/kafka/data
  - name: kafka-config
    mountPath: /etc/kafka-config
    readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  server.properties: |
    num.partitions=1
    listeners=PLAINTEXT://:9092
    log.dirs=/var/lib/kafka/data
    auto.create.topics.enable=true
    zookeeper.connect=zookeeper:2181
    advertised.listeners=PLAINTEXT://broker.kafka.svc.cluster.local:9092,PLAINTEXT_INTERNAL://broker:29092
  config.ini: |
    [default]
    name=gauravj
---
apiVersion: v1
kind: Secret
metadata:
  name: broker-secret
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
---