kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-kafka
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: /home/extd/dev/projects/kubeer/pvdata
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: broker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast

