kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-pods
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        kafka.network/default: "true"
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:7.4.0-2-ubi8
          name: zkdocker
          ports:
            - containerPort: 2181
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
